name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # ─────────────── JOB 1 : BUILD & TEST ───────────────
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bd_todo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: bd_todo
      DB_USER: root
      DB_PASS: root
      JWT_SECRET: ci_secret_test
      JWT_EXPIRES_IN: 1d
      PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
            echo "En attente de MySQL..."
            sleep 2
          done

      - name: Run tests
        run: npm test -- --coverage --forceExit

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  # ─────────────── JOB 2 : DEPLOY ───────────────
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'


    steps:
      - name: Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { serviceInstanceRedeploy(serviceId: \"${{ secrets.RAILWAY_SERVICE_ID }}\", environmentId: \"${{ secrets.RAILWAY_ENVIRONMENT_ID }}\") }"}' \
            https://backboard.railway.app/graphql/v2